export const GET_RECEIVED_DRUG_LIST = "GET_RECEIVED_DRUG_LIST";
export const GET_RECEIVED_DRUG_LIST_RESPONSE =
  "GET_RECEIVED_DRUG_LIST_RESPONSE";
export const GET_RECEIVED_PO_CHALLAN_LIST = "GET_RECEIVED_PO_CHALLAN_LIST";
export const GET_RECEIVED_PO_CHALLAN_LIST_RESPONSE =
  "GET_RECEIVED_PO_CHALLAN_LIST_RESPONSE";
export const GET_ALL_CHALLAN_LIST = "GET_ALL_CHALLAN_LIST";
export const GET_ALL_CHALLAN_LIST_RESPONSE = "GET_ALL_CHALLAN_LIST_RESPONSE";
