export const GET_ISSUE_DESK_LIST = "GET_ISSUE_DESK_LIST";
export const GET_ISSUE_DESK_LIST_RESPONSE = "GET_ISSUE_DESK_LIST_RESPONSE";

export const GET_RETURN_DESK_LIST = "GET_RETURN_DESK_LIST";
export const GET_RETURN_DESK_LIST_RESPONSE = "GET_RETURN_DESK_LIST_RESPONSE";

export const GET_ISSUE_TO_THIRD_PARTY_LIST = "GET_ISSUE_TO_THIRD_PARTY_LIST";
export const GET_ISSUE_TO_THIRD_PARTY_LIST_RESPONSE =
  "GET_ISSUE_TO_THIRD_PARTY_LIST_RESPONSE";

export const GET_INTENT_ISSUE_LIST = "GET_INTENT_ISSUE_LIST";
export const GET_INTENT_ISSUE_LIST_RESPONSE = "GET_INTENT_ISSUE_LIST_RESPONSE";
export const GET_OFFLINE_ISSUE_LIST = "GET_OFFLINE_ISSUE_LIST";
export const GET_OFFLINE_ISSUE_LIST_RESPONSE =
  "GET_OFFLINE_ISSUE_LIST_RESPONSE";
export const GET_ISSUE_CAMP_LIST = "GET_ISSUE_CAMP_LIST";
export const GET_ISSUE_CAMP_LIST_RESPONSE = "GET_ISSUE_CAMP_LIST_RESPONSE";

export const GET_SUB_STORE_RETURN_LIST = "GET_SUB_STORE_RETURN_LIST";
export const GET_SUB_STORE_RETURN_LIST_RESPONSE =
  "GET_SUB_STORE_RETURN_LIST_RESPONSE";

export const GET_THIRD_PARTY_RETURN = "GET_THIRD_PARTY_RETURN";
export const GET_THIRD_PARTY_RETURN_RESPONSE =
  "GET_THIRD_PARTY_RETURN_RESPONSE";

export const GET_MISCELLANOUS_STCK_CONSMP_LIST =
  "GET_MISCELLANOUS_STCK_CONSMP_LIST";
export const GET_MISCELLANOUS_STCK_CONSMP_LIST_RESPONSE =
  "GET_MISCELLANOUS_STCK_CONSMP_LIST_RESPONSE";
export const GET_ADD_MISCELLANOUS_LIST = "GET_ADD_MISCELLANOUS_LIST";
export const GET_ADD_MISCELLANOUS_LIST_RSPONSE =
  "GET_ADD_MISCELLANOUS_LIST_RSPONSE";
