export const GET_ISSUE_DESK_LIST = "GET_ISSUE_DESK_LIST";
export const GET_ISSUE_DESK_LIST_RESPONSE = "GET_ISSUE_DESK_LIST_RESPONSE";

export const GET_RETURN_DESK_LIST = "GET_RETURN_DESK_LIST";
export const GET_RETURN_DESK_LIST_RESPONSE = "GET_RETURN_DESK_LIST_RESPONSE";

export const GET_ISSUE_TO_THIRD_PARTY_LIST = "GET_ISSUE_TO_THIRD_PARTY_LIST";
export const GET_ISSUE_TO_THIRD_PARTY_LIST_RESPONSE =
  "GET_ISSUE_TO_THIRD_PARTY_LIST_RESPONSE";

export const GET_INTENT_ISSUE_LIST = "GET_INTENT_ISSUE_LIST";
export const GET_INTENT_ISSUE_LIST_RESPONSE = "GET_INTENT_ISSUE_LIST_RESPONSE";
export const GET_OFFLINE_ISSUE_LIST = "GET_OFFLINE_ISSUE_LIST";
export const GET_OFFLINE_ISSUE_LIST_RESPONSE =
  "GET_OFFLINE_ISSUE_LIST_RESPONSE";
export const GET_ISSUE_CAMP_LIST = "GET_ISSUE_CAMP_LIST";
export const GET_ISSUE_CAMP_LIST_RESPONSE = "GET_ISSUE_CAMP_LIST_RESPONSE";
