export const GET_INTENT_DRUGS_LIST = "GET_INTENT_DRUGS_LIST";
export const GET_INTENT_DRUGS_LIST_RESPONSE = "GET_INTENT_DRUGS_LIST_RESPONSE";
export const GET_TRANSFER_LIST = "GET_TRANSFER_LIST";
export const GET_TRANSFER_LIST_RESPONSE = "GET_TRANSFER_LIST_RESPONSE";
