export const GET_STOCK_LEDGER = "GET_STOCK_LEDGER";
export const GET_STOCK_LEDGER_RESPONSE = "GET_STOCK_LEDGER_RESPONSE";

export const GET_STOCK_STATUS = "GET_STOCK_STATUS";
export const GET_STOCK_STATUS_RESPONSE = "GET_STOCK_STATUS_RESPONSE";

export const GET_CLASSWISE_DRUG = "GET_CLASSWISE_DRUG";
export const GET_CLASSWISE_DRUG_RESPONSE = "GET_CLASSWISE_DRUG_RESPONSE";

export const POST_STOCK_REPORT = "POST_STOCK_REPORT";
export const POST_STOCK_REPORT_RESPONSE = "POST_STOCK_REPORT_RESPONSE";

export const POST_STATUS_REPORT = "POST_STATUS_REPORT";
export const POST_STATUS_REPORT_RESPONSE = "POST_STATUS_REPORT_RESPONSE";

export const GET_SUBSTORE_BY_STOREID = "GET_SUBSTORE_BY_STOREID";
export const GET_SUBSTORE_BY_STOREID_RESPONSE =
  "GET_SUBSTORE_BY_STOREID_RESPONSE";
