export const GET_NOTIFICATION_LIST = "GET_NOTIFICATION_LIST";
export const GET_NOTIFICATION_LIST_RESPONSE = "GET_NOTIFICATION_LIST_RESPONSE";
export const GET_ALL_OPEN_NOTIFICATION_LIST = "GET_ALL_OPEN_NOTIFICATION_LIST";
export const GET_ALL_OPEN_NOTIFICATION_LIST_RESPONSE =
  "GET_ALL_OPEN_NOTIFICATION_LIST_RESPONSE";
export const GET_DRUG_BY_PROGRAMME_ID = "GET_DRUG_BY_PROGRAMME_ID";
export const GET_DRUG_BY_PROGRAMME_ID_RESPONSE =
  "GET_DRUG_BY_PROGRAMME_ID_RESPONSE";

export const SAVE_DEMAND_NOTIFICATION = "SAVE_DEMAND_NOTIFICATION";
export const SAVE_DEMAND_NOTIFICATION_RESPONSE =
  "SAVE_DEMAND_NOTIFICATION_RESPONSE";

export const CANCEL_NOTIFICATION = "CANCEL_NOTIFICATION";
export const CANCEL_NOTIFICATION_RESPONSE = "CANCEL_NOTIFICATION_RESPONSE";

export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const UPDATE_NOTIFICATION_RESPONSE = "UPDATE_NOTIFICATION_RESPONSE";

export const GET_ANNUAL_DEMAND_NOTIFICATION = "GET_ANNUAL_DEMAND_NOTIFICATION";
export const GET_ANNUAL_DEMAND_NOTIFICATION_RESPONSE =
  "GET_ANNUAL_DEMAND_NOTIFICATION_RESPONSE";

export const SAVE_GENERATE_ANNUAL_DEMAND = "SAVE_GENERATE_ANNUAL_DEMAND";
export const SAVE_GENERATE_ANNUAL_DEMAND_RESPONSE =
  "SAVE_GENERATE_ANNUAL_DEMAND_RESPONSE";

export const GET_COMPILE_DEMAND = "GET_COMPILE_DEMAND";
export const GET_COMPILE_DEMAND_REPONSE = "GET_COMPILE_DEMAND_REPONSE";

export const SAVE_COMPILE_DEMAND = "SAVE_COMPILE_DEMAND";
export const SAVE_COMPILE_DEMAND_RESPONSE = "SAVE_COMPILE_DEMAND_RESPONSE";
