export const GET_APPROVAL_DESK_LIST = "GET_APPROVAL_DESK_LIST";
export const GET_APPROVAL_DESK_LIST_RESPONSE =
  "GET_APPROVAL_DESK_LIST_RESPONSE";
export const GET_PURCHASE_ORDER_LIST_FOR_APPROVAL = "GET_PURCHASE_ORDER_LIST";
export const GET_PURCHASE_ORDER_LIST_FOR_APPROVAL_RESPONSE =
  "GET_PURCHASE_ORDER_LIST_RESPONSE";

export const GET_APPROVAL_INTENT_APPROVAL_LIST =
  "GET_APPROVAL_INTENT_APPROVAL_LIST";
export const GET_APPROVAL_INTENT_APPROVAL_LIST_RESPONSE =
  "GET_APPROVAL_INTENT_APPROVAL_LIST_RESPONSE";

export const GET_TRANSFER_APPROVAL_LIST = "GET_TRANSFER_APPROVAL_LIST";
export const GET_TRANSFER_APPROVAL_LIST_RESPONSE =
  "GET_TRANSFER_APPROVAL_LIST_RESPONSE";

export const GET_TRANSFER_APPROVAL_LIST_HQ = "GET_TRANSFER_APPROVAL_LIST_HQ";
export const GET_TRANSFER_APPROVAL_LIST_HQ_RESPONSE =
  "GET_TRANSFER_APPROVAL_LIST_HQ_RESPONSE";
