export const GET_APPROVAL_DESK_LIST = "GET_APPROVAL_DESK_LIST";
export const GET_APPROVAL_DESK_LIST_RESPONSE =
  "GET_APPROVAL_DESK_LIST_RESPONSE";
export const GET_PURCHASE_ORDER_LIST_FOR_APPROVAL =
  "GET_PURCHASE_ORDER_LIST_FOR_APPROVAL";
export const GET_PURCHASE_ORDER_LIST_FOR_APPROVAL_RESPONSE =
  "GET_PURCHASE_ORDER_LIST_RESPONSE";

export const GET_APPROVAL_INTENT_APPROVAL_LIST =
  "GET_APPROVAL_INTENT_APPROVAL_LIST";
export const GET_APPROVAL_INTENT_APPROVAL_LIST_RESPONSE =
  "GET_APPROVAL_INTENT_APPROVAL_LIST_RESPONSE";

export const GET_TRANSFER_APPROVAL_LIST = "GET_TRANSFER_APPROVAL_LIST";
export const GET_TRANSFER_APPROVAL_LIST_RESPONSE =
  "GET_TRANSFER_APPROVAL_LIST_RESPONSE";

export const GET_TRANSFER_APPROVAL_LIST_HQ = "GET_TRANSFER_APPROVAL_LIST_HQ";
export const GET_TRANSFER_APPROVAL_LIST_HQ_RESPONSE =
  "GET_TRANSFER_APPROVAL_LIST_HQ_RESPONSE";
export const GET_MANUFACTURING_DESK_LIST = "GET_MANUFACTURING_DESK_LIST";
export const GET_MANUFACTURING_DESK_LIST_RESPONSE =
  "GET_MANUFACTURING_DESK_LIST_RESPONSE";

export const GET_CENTRAL_PURCHASE_LIST = "GET_CENTRAL_PURCHASE_LIST";
export const GET_CENTRAL_PURCHASE_LIST_RESPONSE =
  "GET_CENTRAL_PURCHASE_LIST_RESPONSE";

export const CREATE_MANUFACTURING = "CREATE_MANUFACTURING";
export const CREATE_MANUFACTURING_RESPONSE = "CREATE_MANUFACTURING_RESPONSE";

export const EDIT_MANUFACTURING = "EDIT_MANUFACTURING";
export const EDIT_MANUFACTURING_RESPONSE = "EDIT_MANUFACTURING_RESPONSE";

export const GET_ANNUAL_DEMAND_BY_NOTIFICATION_ID =
  "GET_ANNUAL_DEMAND_BY_NOTIFICATION_ID";
export const GET_ANNUAL_DEMAND_BY_NOTIFICATION_ID_RESPONSE =
  "GET_ANNUAL_DEMAND_BY_NOTIFICATION_ID_RESPONSE";

export const APPROVE_ANNUAL_DEMAND = "APPROVE_ANNUAL_DEMAND";
export const APPROVE_ANNUAL_DEMAND_RESPONSE = "APPROVE_ANNUAL_DEMAND_RESPONSE";

export const GET_NEW_RATE_CONTRACT_LIST = "GET_NEW_RATE_CONTRACT_LIST";
export const GET_NEW_RATE_CONTRACT_LIST_RESPONSE =
  "GET_NEW_RATE_CONTRACT_LIST_RESPONSE";
export const ADD_NEW_CONTRACT_RATE = "ADD_NEW_CONTRACT_RATE";
export const ADD_NEW_CONTRACT_RATE_RESPONSE = "ADD_NEW_CONTRACT_RATE_RESPONSE";

export const RENEW_RATE_CONTRACT = "RENEW_RATE_CONTRACT";
export const RENEW_RATE_CONTRACT_RESPONSE = "RENEW_RATE_CONTRACT_RESPONSE";

export const INACTIVE_RATE_CONTRACT = "INACTIVE_RATE_CONTRACT";
export const INACTIVE_RATE_CONTRACT_RESPONSE =
  "INACTIVE_RATE_CONTRACT_RESPONSE";

export const POST_RENEW_RATE_CONTRACT = "POST_RENEW_RATE_CONTRACT";
export const POST_RENEW_RATE_CONTRACT_RESPONSE =
  "POST_RENEW_RATE_CONTRACT_RESPONSE";

export const GET_FREEZE_NOTI_DETAILS = "GET_FREEZE_NOTI_DETAILS";
export const GET_FREEZE_NOTI_DETAILS_RESPONSE =
  "GET_FREEZE_NOTI_DETAILS_RESPONSE";
export const PROCESS_PO = "PROCESS_PO";
export const PROCESS_PO_RESPONSE = "PROCESS_PO_RESPONSE";
export const CREATE_PO = "CREATE_PO";
export const CREATE_PO_RESPONSE = "CREATE_PO_RESPONSE";
export const GET_PROCESS_ORDER_PROCESS_INFO = "GET_PROCESS_ORDER_PROCESS_INFO";
export const GET_PROCESS_ORDER_PROCESS_INFO_RESPONSE =
  "GET_PROCESS_ORDER_PROCESS_INFO_RESPONSE";
export const GET_LOCAL_PO_INFO = "GET_LOCAL_PO_INFO";
export const GET_LOCAL_PO_INFO_RESPOSNE = "GET_LOCAL_PO_INFO_RESPOSNE";

export const CREATE_LOCAL_PO = "CREATE_LOCAL_PO";
export const CREATE_LOCAL_PO_RESPONSE = "CREATE_LOCAL_PO_RESPONSE";

export const CANCEL_PO = "CANCEL_PO";
export const CANCEL_PO_RESPONSE = "CANCEL_PO_RESPONSE";
