export const GET_STOCK_DESK_LIST = "GET_STOCK_DESK_LIST";
export const GET_STOCK_DESK_LIST_RESPONSE = "GET_STOCK_DESK_LIST_RESPONSE";

export const ADD_STOCK_ENTRY = "ADD_STOCK_ENTRY";
export const ADD_STOCK_ENTRY_RESPONSE = "ADD_STOCK_ENTRY_RESPONSE";

export const GET_STOCK_ENTRY_DESK = "GET_STOCK_ENTRY_DESK";
export const GET_STOCK_ENTRY_DESK_RESPONSE = "GET_STOCK_ENTRY_DESK_RESPONSE";

export const GET_UPDATE_STOCK_RACK_LIST = "GET_UPDATE_STOCK_RECK_LIST";
export const GET_UPDATE_STOCK_RACK_LIST_RESPONSE =
  "GET_UPDATE_STOCK_RECK_LIST_RESPONSE";

export const GET_STOCK_VERIFICATION_LIST = "GET_STOCK_VERIFICATION_LIST";
export const GET_STOCK_VERIFICATION_LIST_RESPONSE =
  "GET_STOCK_VERIFICATION_LIST_RESPONSE";
