export const DELETE_ROLE = "DELETE_ROLE";
export const ROLE_DELETED_SUCCESSFULL = "ROLE_DELETED_SUCCESSFULL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_RESPONSE = "DELETE_USER_RESPONSE";

export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_RESPONSE = "GET_USER_LIST_RESPONSE";
export const GET_DRUG_DESK_LIST = "GET_DRUG_DESK_LIST";
export const GET_DRUG_DESK_LIST_RESPONSE = "GET_DRUG_DESK_LIST_RESPONSE";
export const GET_ROLE_LIST = "GET_ROLE_LIST";
export const GET_ROLE_LIST_RESPONSE = "GET_ROLE_LIST_RESPONSE";

export const EDIT_ROLE = "EDIT_ROLE";
export const EDIT_ROLE_RESPONSE = "EDIT_ROLE_RESPONSE";
export const GET_PROGRAM_DESK_LIST = "GET_PROGRAM_DESK_LIST";
export const GET_PROGRAM_DESK_LIST_RESPONSE = "GET_PROGRAM_DESK_LIST_RESPONSE";
export const GET_STORE_DESK_LIST = "GET_STORE_DESK_LIST";
export const GET_STORE_DESK_LIST_RESPONSE = "GET_STORE_DESK_LIST_RESPONSE";

export const EDIT_STORE_RECORD = "EDIT_STORE_RECORD";
export const EDIT_STORE_RECORD_RESPONSE = "EDIT_STORE_RECORD_RESPONSE";

export const DELETE_STORE_RECORD = "DELETE_STORE_RECORD";
export const DELETE_STORE_RECORD_RESPONSE = "DELETE_STORE_RECORD_RESPONSE";

export const GET_PURCHASE_ORDER_LIST = "GET_PURCHASE_ORDER_LIST";
export const GET_PURCHASE_ORDER_LIST_RESPONSE =
  "GET_PURCHASE_ORDER_LIST_RESPONSE";
export const GET_SUPPLIER_LIST = "GET_SUPPLIER_LIST";
export const GET_SUPPLIER_LIST_RESPONSE = "GET_SUPPLIER_LIST_RESPONSE";
export const GET_RATE_CONTRACT_DESK_LIST = "GET_RATE_CONTRACT_DESK_LIST";
export const GET_RATE_CONTRACT_DESK_LIST_RESPONSE =
  "GET_RATE_CONTRACT_DESK_LIST_RESPONSE";
export const GET_FUNDING_SOURCE_LIST = "GET_FUNDING_SOURCE_LIST";
export const GET_FUNDING_SOURCE_LIST_RESPONSE =
  "GET_FUNDING_SOURCE_LIST_RESPONSE";
export const GET_BUDGET_INTERFACE_LIST = "GET_BUDGET_INTERFACE_LIST";
export const GET_BUDGET_INTERFACE_LIST_RESPONSE =
  "GET_BUDGET_INTERFACE_LIST_RESPONSE";

export const GET_BUDGET_DETAILS = "GET_BUDGET_DETAILS";
export const GET_BUDGET_DETAILS_RESPONSE = "GET_BUDGET_DETAILS_RESPONSE";

export const CREATE_NEW_BUDGET_DESK = "CREATE_NEW_BUDGET_DESK";
export const CREATE_NEW_BUDGET_DESK_RESPONSE =
  "CREATE_NEW_BUDGET_DESK_RESPONSE";

// export const GET_DRUG_LIST

// POST
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_RESPONSE = "CREATE_USER_RESPONSE";

export const CREATE_NEW_DRUG = "CREAT_NEW_DRUG";
export const CREATE_NEW_DRUG_RESPONSE = "CREATE_NEW_DRUG_RESPONSE";

export const CREATE_STORE = "CREATE_STORE";
export const CREATE_STORE_RESPONSE = "CREATE_STORE_RESPONSE";

export const CREATE_PROGRAM = "CREATE_PROGRAM";
export const CREATE_PORGRAM_RESPONSE = "CREATE_PORGRAM_RESPONSE";

export const UPDATE_PROGRAM = "UPDATE_PROGRAM";
export const UPDATE_PROGRAM_RESPONSE = "UPDATE_PROGRAM_RESPONSE";

export const DELETE_PROGRAM = "DELETE_PROGRAM";
export const DELETE_PROGRAM_RESPONSE = "DELETE_PROGRAM_RESPONSE";

export const CREATE_ROLE = "CREATE_ROLE";
export const CREATE_ROLE_RESPONSE = "CREATE_ROLE_RESPONSE";

export const GET_ACTIVITY_LIST_BY_ROLE_ID = "GET_ACTIVITY_LIST_BY_ROLE_ID";
export const GET_ACTIVITY_LIST_BY_ROLE_ID_RESPONSE =
  "GET_ACTIVITY_LIST_BY_ROLE_ID_RESPONSE";

export const EDIT_NEW_FUNDING = "EDIT_NEW_FUNDING";
export const EDIT_NEW_FUNDING_RESPONSE = "EDIT_NEW_FUNDING_RESPONSE";

export const POST_EDL_MAPPING = "POST_EDL_MAPPING";
export const POST_EDL_MAPPING_RESPONSE = "POST_EDL_MAPPING_RESPONSE";

export const POST_PROGRAM_FUND_MAPPING = "POST_PROGRAM_FUND_MAPPING";
export const POST_PROGRAM_FUND_MAPPING_RESPONSE =
  "POST_PROGRAM_FUND_MAPPING_RESPONSE";

export const CREATE_NEW_BUDGET = "CREATE_NEW_BUDGET";
export const CREATE_NEW_BUDGET_RESPONSE = "CREATE_NEW_BUDGET_RESPONSE";

export const GET_EDL_MAPPING = "GET_EDL_MAPPING";
export const GET_EDL_MAPPING_RESPONSE = "GET_EDL_MAPPING_RESPONSE";

export const CREATE_EDL_MAPPING = "CREATE_EDL_MAPPING";
export const CREATE_EDL_MAPPING_RESPONSE = "CREATE_EDL_MAPPING_RESPONSE";

export const GET_PROGRAM_FUNDING_SOURCE = "GET_PROGRAM_FUNDING_SOURCE";
export const GET_PROGRAM_FUNDING_SOURCE_RESPONSE =
  "GET_PROGRAM_FUNDING_SOURCE_RESPONSE";
export const GET_PROGRAM_FUNDING_SOURCE_BY_PRGNAME =
  "GET_PROGRAM_FUNDING_SOURCE_BY_PRGNAME";
export const GET_PROGRAM_FUNDING_SOURCE_BY_PRGNAME_RESPONSE =
  "GET_PROGRAM_FUNDING_SOURCE_BY_PRGNAME_RESPONSE";

export const GET_FUNDING_SOURCE_BY_PORGRM_NAME =
  "GET_FUNDING_SOURCE_BY_PORGRM_NAME";
export const GET_FUNDING_SOURCE_BY_PORGRM_NAME_RESPONSE =
  "GET_FUNDING_SOURCE_BY_PORGRM_NAME_RESPONSE";

export const CREATE_PROGRAM_FUNDING = "CREATE_PROGRAM_FUNDING";
export const CREATE_PROGRAM_FUNDING_RESPONSE =
  "CREATE_PROGRAM_FUNDING_RESPONSE";

export const GET_DRUG_LIST_BY_STORE_TYPE = "GET_DRUG_LIST_BY_STORE_TYPE";
export const GET_DRUG_LIST_BY_STORE_TYPE_RESPONSE =
  "GET_DRUG_LIST_BY_STORE_TYPE_RESPONSE";

export const DELETE_DRUG = "DELETE_DRUG";
export const DELETE_DRUG_RESPONSE = "DELETE_DRUG_RESPONSE";
export const EDIT_DRUG = "EDIT_DRUG";
export const EDIT_DRUG_RESPONSE = "EDIT_DRUG_RESPONSE";
//Funding Record
export const CREATE_NEW_FUNDING = "CREATE_NEW_FUNDING";
export const CREATE_NEW_FUNDING_RESPONSE = "CREATE_NEW_FUNDING_RESPONSE";

export const UPDATE_FUNDING_RECORD = "UPDATE_FUNDING_RECORD";
export const UPDATE_FUNDING_RECORD_RSPONSE = "UPDATE_FUNDING_RECORD_RSPONSE";

export const DELETE_FUNDING_RECORD = "DELETE_FUNDING_RECORD";
export const DELETE_FUNDING_RECORD_RESPONSE = "DELETE_FUNDING_RECORD_RESPONSE";
